name: SudokuPencil
options:
  bundleIdPrefix: com.fbn3799
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
targets:
  SudokuPencil:
    type: application
    platform: iOS
    sources:
      - Sources
    info:
      path: Info.plist
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.fbn3799.sudoku-pencil
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: ""
